### ISSUE TITLE
Where can i access the git repo for Ids enterprise ng

### ISSUE THREAD

**Issue by RANDOMUSER5016** [infor-design/ids-stylesonly-demos#2]
this is throwing 404 now and other url for infor is not accessible?
Is it paid now? or still i can access it somewhere else?

https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts

**Comment by tmcconechy** [comment]
@RANDOMUSER5016 We moved our repos internally to our oxford instance for several reasons but they are not "paid".

https://oxford.awsdev.infor.com/infor-design/enterprise-ng

- If you are an infor user with access to oxford you should be ok.
- If you are infor user with no access use the SAAM tool to get access
- If you are partner and not an info user contact Gaetano Pollice <gaetano.pollice@infor.com> and mention you would like access to the repos.

Sorry for the confusion.
